name: BoomMinecart
main: tk.a08381.BoomMinecart
version: 1.5
author: a08381
permissions: 
    BoomMinecart.broadcast:
        default: op
    BoomMinecart.seelog:
        default: op
    BoomMinecart.checkup:
        default: op
